version: "3.9"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ~/db/mongo/data:/data/db
  mongoexp:
    image: mongo-express:latest
    ports:
      - 127.0.0.1:8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
